---
title: "Test_analysis_R_microbes"
author: "Macrofauna"
date: "2026-03-11"
output: html_document
---
# 1 Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE,
                      message = FALSE
)
```

# 2 Load libraries

```{r libraries}
suppressPackageStartupMessages(
  library(tidyverse)
  )
suppressPackageStartupMessages(
  library(ggpubr)
  )
suppressPackageStartupMessages(
  library(naniar)
  )
suppressPackageStartupMessages(
  library (vegan)
  )
suppressPackageStartupMessages(
  library (SRS)
  )
```

# 3 Data Import

```{r Data import}
# Metadata (sample informatrion)
meta <- read.csv("16S-microbiome-analysis-R/data//meta.microbes.csv", 
                 header=T, 
                 stringsAsFactors = F)

# ASV count table
counts <- read.table("16S-microbiome-analysis-R/data/ASV_table_microbes.tsv", 
                     stringsAsFactors = F, 
                     header =T)%>%
          gather(
            sample,
            count, 
            2:ncol(.)
            )%>%
          filter(count > 0)

# Taxonomy table
taxa <- read.delim("16S-microbiome-analysis-R/data/ASV_tax.gtdb.tsv",
                   stringsAsFactors = FALSE, 
                   header=TRUE)
```

# 4 Data Preprocessing

```{r data_preprocessing}
taxa <- taxa %>%
     replace_with_na(list(
            Kingdom="",
          Phylum="",
          Class="",
          Order="",
          Family="",
          Genus="",
          Species=""
          ))%>%
        replace_na(list(
          Kingdom="zz_Unclassified",
          Phylum="zz_Unclassified",
          Class="zz_Unclassified",
          Order="zz_Unclassified",
          Family="zz_Unclassified",
          Genus="zz_Unclassified",
          Species="zz_Unclassified"))

# Merge counts, metadata and taxonomy
Table <- counts%>% 
  left_join(meta, by="sample") %>% 
  left_join(taxa, by="ASV_ID")
```
# Quality Control

## Sequencing Depth
```{r Quality Control}

## Sequencing depth

Table$depth<-factor(
  Table$depth,
  levels=c("0-1cm", "1-2cm" ,"5-6cm", "8-10cm", "15-17cm")
  )

Table%>% 
  group_by(sample, depth, site) %>%  
  summarize(count = sum(count)) %>% 
  ungroup() %>%
  ggplot(aes(x = sample, y = count, color=depth, shape=site)) + 
  geom_point(size=6) +  
  coord_flip() + 
  theme_classic()+
  ggtitle("Sequencing depth per Sample")

##Sequencing depth was evaluated to ensure sufficient coverage across samples and to identify potential outliers with low read counts.






```

## Rarefaction Curve

```{r rarefaction}

Table_wide <-Table %>%
  dplyr::select(ASV_ID, sample, count) %>% 
  spread(ASV_ID,count, fill= 0) %>%
  remove_rownames() %>% 
  column_to_rownames(var = "sample")

(raremax <- min(rowSums(Table_wide)))

rarecurve(Table_wide, step = 20, sample = raremax , cex = 0.6)

##Rarefaction curves were used to evaluate whether sequencing depth was sufficient to capture the majority of microbial diversity.

```

## Relative Abundance Calculation

```{r relative_abundance}

Table <- Table%>%
    group_by(sample) %>% 
  filter(sum(count) >= 1000) %>% 
  mutate(relab = count/sum(count)) %>%
  ungroup()


```

## Top Phyla
```{r top_phyla}

top_phyla <-Table %>%
  group_by(Phylum) %>%
  summarise(mean_abundance = mean(relab)) %>%
  arrange(desc(mean_abundance))

head(top_phyla, 10)

top10 <- top_phyla %>%
  slice_max(mean_abundance, n = 10)

ggplot(top10,
       aes(x = reorder(Phylum, mean_abundance),
           y = mean_abundance)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(x = "Phylum",
       y = "Mean Relative Abundance",
       title = "Top 10 Phyla")

#relative abundance profiles were inspected to detect dominant taxa across samples.
```
# 6 Diversity Analysis

##Alpha Diversity

###SRS Normalization

```{r srs_normalization}

example_input_data <- Table %>%
  group_by(ASV_ID, sample)%>%
 summarise(count=sum(count))%>%
   ungroup()%>%
  dplyr::select(ASV_ID, sample, count)%>%
  spread(sample,count, fill= 0) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "ASV_ID")

Cmin <- min(colSums(example_input_data))
Cmin

SRS_output <- SRS(data = example_input_data, Cmin = Cmin)

```
### Shannon Diversity

```{r shannon_diversity}

SRSshannon<- SRS_output %>%
  t()%>%
  data.frame()%>% 
  rownames_to_column(var="sample")%>% 
  plyr::ddply(~sample, 
              function(x) 
                {vegan::diversity(x[-1],
                            index="shannon")})%>%
  dplyr::rename(shannon= V1) %>% 
  left_join(meta, by="sample")

```

### Alpha Diversity Plot

```{r alpha_plot}

SRSshannon$depth<-factor( 
  SRSshannon$depth,
              levels=c("0-1cm", "1-2cm" ,"5-6cm", "8-10cm", "15-17cm")
  )

SRSshannon %>%
  group_by(depth,site,sample)%>%
 ggplot(aes(x = sample, 
            y = shannon, 
            color=depth, 
            shape=site)) +
   geom_point(size=5) +
  guides(size=guide_legend(
    order=2),
         shape= guide_legend(override.aes=list(
           size=2),
        colour=guide_legend(override.aes=list(
          size=4))))+
    theme_classic()+
  theme(axis.text.x=element_text(angle = -45, hjust = 0)
        )

#Alpha diversity metrics were calculated to evaluate differences in microbial diversity across sample groups.
```
# 7 Beta Diversity

## NMDS

```{r nmds}

df_nmds <-  Table%>% 
  dplyr::select(ASV_ID,sample,relab) %>% 
  spread(ASV_ID,relab, fill= 0) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "sample")

nmds.asvs.h.bc <- metaMDS(df_nmds ,
                             distance = "bray",
                             k = 3,
                             trymax = 50,
                             autotransform = FALSE,
                             trace = FALSE)


nmds.seed.asvs.bc.df <- as.data.frame(
  nmds.asvs.h.bc$points) %>%
      rownames_to_column(
        var ="sample") %>%
       dplyr::rename(NMDS1 = MDS1, NMDS2 = MDS2)


```

### NMDS Plot
```{r nmds_plot}
 nmds.seed.asvs.bc.df %>% 
  inner_join (meta, by="sample")%>%
  ungroup()%>%
  ggplot( aes(x=NMDS1, y=NMDS2, color=depth, shape=site)) +
  geom_point(size = 4) +
  theme_classic() +
  theme(legend.position = "bottom")+
  labs(title = "NMDS")
```

# 8 Taxonomic Composition
```{r taxonomy_plot}
Table %>%
  group_by(sample)%>%
  filter(relab >0.01)%>%
ggplot(aes(x = depth, y = relab, fill = Phylum)) +
geom_bar(stat="identity", position="fill") +
coord_flip() +
theme(
    legend.position = 'bottom'
  )+
  xlab('sample') + ylab('relative abundance') +
  ggtitle("relab per sample >1% Phylum")+
   theme_classic()+
  theme(
    legend.position = 'bottom',
    axis.text.x = element_text(angle = 60, hjust = 1)
  )+
  facet_wrap(~site)
```
# 9 Session Information

```{r session_info}

sessionInfo()


Sys.time()

```
